export const SPIDERMESH_UDP_BROADCAST_ADDRESS = process.env.SPIDERMESH_UDP_BROADCAST_ADDRESS || ''
export const SPIDERMESH_UDP_BROADCAST_PORT = Number(process.env.SPIDERMESH_UDP_BROADCAST_PORT || 20000)

export const SPIDERMESH_TLS_KEY_PATH = process.env.SPIDERMESH_TLS_KEY_PATH
export const SPIDERMESH_TLS_CERT_PATH = process.env.SPIDERMESH_TLS_CERT_PATH
export const SPIDERMESH_TLS_CA_PATH = process.env.SPIDERMESH_TLS_CA_PATH