export const SPIDERMESH_HTTP2_RECONNECT_ATTEMPTS = Number(process.env.SPIDERMESH_HTTP2_RECONNECT_ATTEMPTS || 3)
export const SPIDERMESH_HTTP2_RECONNECT_DELAY_MS = Number(process.env.SPIDERMESH_HTTP2_RECONNECT_DELAY_MS || 250)
export const SPIDERMESH_HTTP2_CONNECT_TIMEOUT_MS = Number(process.env.SPIDERMESH_HTTP2_CONNECT_TIMEOUT_MS || 2000)
