export const SPIDERMESH_WHITELIST_ADDRESS = process.env.SPIDERMESH_WHITELIST_ADDRESS
export const SPIDERMESH_MULTICAST_PORT = Number(process.env.SPIDERMESH_MULTICAST_PORT || 20002)
export const SPIDERMESH_HTTP2_AUTO_LOAD_BALANCE = !process.env.SPIDERMESH_HTTP2_AUTO_LOAD_BALANCE
export const SPIDERMESH_MULTICAST_ADDRESS = process.env.SPIDERMESH_MULTICAST_ADDRESS ||  "239.0.0.3"